name: Xiaojiu
main: xiaojiu.StartPlugins
version: 1
author: Xiaojiu

commands:
  xiaojiu:
    description: main command
    aliases:
      - xj
  restartserver:
    description: Restart the server
    aliases:
      - rest
      - rs
  safeguard:
    description: server maintain
    aliases:
      - sg
  Limit:
    description: Limit Player
    aliases:
      - Li
      - li
  suggest:
    description: suggest
    aliases:
      - sug
  playerTime:
    description: Get Time
    aliases:
      - pt
      - time
permissions:
  xiaojiu.op:
    default: op
    children:
#      xiaojiu.PlayerLimit.help: true
      xiaojiu.op.PlayerLimit.add: true
      xiaojiu.op.PlayerLimit.remove: true
      xiaojiu.op.PlayerLimit.save: true
#      xiaojiu.PlayerTime.help: true
      xiaojiu.op.PlayerTime.find: true
      xiaojiu.op.PlayerTime.save: true
#      xiaojiu.op.SafeGuard.help: true
      xiaojiu.op.SafeGuard.now: true
      xiaojiu.op.SafeGuard.start: true
      xiaojiu.op.SafeGuard.end: true
      xiaojiu.op.SafeGuard.cancel: true
#      xiaojiu.op.restart.help: true
      xiaojiu.op.restart.now: true
      xiaojiu.op.restart.start: true
      xiaojiu.op.restart.cancel: true
      xiaojiu.op.restart.reset: true
#      xiaojiu.op.ReloadTask.help: true
      xiaojiu.op.ReloadTask.cancel: true
      xiaojiu.op.ReloadTask.down: true
#      xiaojiu.op.ReloadTask.start: false
#      xiaojiu.op.ReloadTask.revoke: false
#      xiaojiu.op.ReloadTask.agree: false
#      xiaojiu.op.ReloadTask.refuse: false
  xiaojiu.normal:
    default: true
    children:
#      help 命令
      xiaojiu.normal.PlayerLimit.help: true
      xiaojiu.normal.PlayerTime.help: true
      xiaojiu.normal.SafeGuard.help: true
      xiaojiu.normal.restart.help: true
      xiaojiu.normal.ReloadTask.help : true
#      ReloadTask 命令
      xiaojiu.normal.ReloadTask.start: true
      xiaojiu.normal.ReloadTask.revoke: true
      xiaojiu.normal.ReloadTask.agree: true
      xiaojiu.normal.ReloadTask.refuse: true