 name: XiaojiuTimeRecord
 main: Xiaojiu.StartPlugins
 version: 1
 author: Xiaojiu

 commands:
   restartserver:
     description: Restart the server
     aliases:
       - rest
       - rs
   safeguard:
     description: server maintain
     aliases:
       - sg
