 name: XiaojiuTimeRecord
 main: xiaojiu.StartPlugins
 version: 1
 author: Xiaojiu

 commands:
   restartserver:
     description: Restart the server
     aliases:
       - rest
       - rs
   safeguard:
     description: server maintain
     aliases:
       - sg
   Limit:
     description: Limit Player
     aliases:
       - Li
       - li