name: XiaojiuTimeRecord
main: xiaojiu.StartPlugins
version: 1
author: Xiaojiu

commands:
  restartserver:
    description: Restart the server
    aliases:
      - rest
      - rs
  safeguard:
    description: server maintain
    aliases:
      - sg
  Limit:
    description: Limit Player
    aliases:
      - Li
      - li
  suggest:
    description: suggest
    aliases:
      - sug
  playerTime:
    description: Get Time
    aliases:
      - pt
      - time
permissions:
  xiaojiu:
    default: op
    children:
      xiaojiu.PlayerLimit.add: true
      xiaojiu.PlayerLimit.remove: true
      xiaojiu.PlayerLimit.save: true
      xiaojiu.PlayerTime.find: true
      xiaojiu.PlayerTime.save: true
      xiaojiu.SafeGuard.now: true
      xiaojiu.SafeGuard.start: true
      xiaojiu.SafeGuard.end: true
      xiaojiu.SafeGuard.cancel: true
      xiaojiu.restart.now: true
      xiaojiu.restart.start: true
      xiaojiu.restart.cancel: true
      xiaojiu.restart.reset: true
      xiaojiu.ReloadTask.cancel: true
      xiaojiu.ReloadTask.down: true
      xiaojiu.ReloadTask.start: false
      xiaojiu.ReloadTask.revoke: false
      xiaojiu.ReloadTask.agree: false
      xiaojiu.ReloadTask.refuse: false